# Generated by Django 3.2 on 2022-06-26 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='shipping to', max_length=100, verbose_name='Address Name')),
                ('address_type', models.CharField(blank=True, choices=[('BILLING', 'Billing Address'), ('SHIPPING', 'Shipping Address')], max_length=100, verbose_name='Address Type')),
                ('address_line_1', models.CharField(blank=True, max_length=120, verbose_name='Address Line 1')),
                ('address_line_2', models.CharField(blank=True, max_length=120, verbose_name='Address Line 2')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='City Name')),
                ('state', models.CharField(blank=True, max_length=120, verbose_name='State Name')),
                ('pincode', models.IntegerField(blank=True, null=True, verbose_name='Pincode')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
