# Generated by Django 3.2 on 2022-07-06 15:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20220628_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format +919999999999             Upto 13 digits', regex='^\\+?\\d{10,13}$')], verbose_name='Phone Number'),
        ),
    ]
