# Generated by Django 3.2 on 2022-06-01 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Product Name')),
                ('image', models.CharField(blank=True, max_length=20, verbose_name='Product Image')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Brand Name')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Product Type/Category')),
                ('description', models.TextField(blank=True, verbose_name='Product Description')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True, verbose_name='Product Rating')),
                ('num_reviews', models.IntegerField(blank=True, default=0, null=True, verbose_name='No. of Reviews')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Price')),
                ('count_in_stock', models.IntegerField(blank=True, default=0, null=True, verbose_name='Count in stock')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
