# Generated by Django 3.2 on 2022-06-01 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Price')),
                ('tax_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Tax')),
                ('shipping_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Shipping Price')),
                ('is_paid', models.BooleanField(blank=True, default=False, null=True, verbose_name='Paid?')),
                ('payment_method', models.CharField(blank=True, choices=[('COD', 'Cash On Delivery'), ('CARD', 'Debit / Credit'), ('UPI', 'Upi'), ('ONLINE', 'Online Netbanking')], default=None, max_length=30, verbose_name='Payment method')),
                ('delivery_status', models.CharField(blank=True, choices=[('NOT_DISPATCHED', 'Not Dispatched'), ('DISPATCHED', 'Dispatched'), ('OTW', 'On The Way'), ('DELIVEREDE', 'Delivered')], default=None, max_length=30, verbose_name='Payment method')),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
