# Generated by Django 3.2 on 2022-06-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_created_order_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('GAMING', 'Games'), ('MOVIES', 'Movies'), ('SHOWS', 'Shows'), ('COMICS', 'Comics')], max_length=100, verbose_name='Product Type/Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Product Image'),
        ),
    ]
