# Generated by Django 3.2 on 2022-06-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_order_delivery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='images/default_img.png', null=True, upload_to='images', verbose_name='Product Image'),
        ),
    ]
