# Generated by Django 3.2 on 2022-07-02 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
