# Generated by Django 3.2 on 2022-07-02 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=120, verbose_name='Order ID')),
                ('delivery_status', models.CharField(blank=True, choices=[('NOT_DISPATCHED', 'Not Dispatched'), ('DISPATCHED', 'Dispatched'), ('OTW', 'On The Way'), ('DELIVERED', 'Delivered')], max_length=30, verbose_name='Delivery Status')),
                ('tax_price', models.DecimalField(blank=True, decimal_places=2, default=18.0, max_digits=10, null=True, verbose_name='Tax')),
                ('shipping_price', models.DecimalField(blank=True, decimal_places=2, default=50.0, max_digits=10, null=True, verbose_name='Shipping Price')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True, verbose_name=' Total Price')),
                ('is_paid', models.BooleanField(blank=True, default=False, null=True, verbose_name='Paid?')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.cart')),
            ],
        ),
    ]
