# Generated by Django 3.2 on 2022-07-07 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20220706_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(blank=True, choices=[('NOT_DISPATCHED', 'Not Dispatched'), ('DISPATCHED', 'Dispatched'), ('OTW', 'On The Way'), ('DELIVERED', 'Delivered')], default='NOT_DISPATCHED', max_length=30, verbose_name='Delivery Status'),
        ),
    ]
